-- Auto-generated KIE standard billing rules (idempotent)
BEGIN TRANSACTION;

DELETE FROM system_api_billing_rules WHERE name LIKE 'KIE Auto Std %';

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (240, 'KIE Auto Std flux-2/flex-image-to-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (240, 'KIE Auto Std flux-2/flex-image-to-image #1', 'Auto std rule for flux-2/flex-image-to-image: ASPECT_RATIO=1:1, RESOLUTION_TIER=K1', 1, 100, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"1:1","RESOLUTION_TIER":"K1"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (241, 'KIE Auto Std flux-2/flex-text-to-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (241, 'KIE Auto Std flux-2/flex-text-to-image #1', 'Auto std rule for flux-2/flex-text-to-image: ASPECT_RATIO=1:1, RESOLUTION_TIER=K1', 1, 100, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"1:1","RESOLUTION_TIER":"K1"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (242, 'KIE Auto Std flux-2/pro-image-to-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (242, 'KIE Auto Std flux-2/pro-image-to-image #1', 'Auto std rule for flux-2/pro-image-to-image: ASPECT_RATIO=1:1, RESOLUTION_TIER=K1', 1, 100, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"1:1","RESOLUTION_TIER":"K1"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (243, 'KIE Auto Std flux-2/pro-text-to-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (243, 'KIE Auto Std flux-2/pro-text-to-image #1', 'Auto std rule for flux-2/pro-text-to-image: ASPECT_RATIO=1:1, RESOLUTION_TIER=K1', 1, 100, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"1:1","RESOLUTION_TIER":"K1"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (245, 'KIE Auto Std google/imagen4 Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (245, 'KIE Auto Std google/imagen4 #1', 'Auto std rule for google/imagen4: ASPECT_RATIO=1:1', 1, 90, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"1:1"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (246, 'KIE Auto Std google/imagen4-fast Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (246, 'KIE Auto Std google/imagen4-fast #1', 'Auto std rule for google/imagen4-fast: ASPECT_RATIO=16:9', 1, 90, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (247, 'KIE Auto Std google/imagen4-ultra Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (247, 'KIE Auto Std google/imagen4-ultra #1', 'Auto std rule for google/imagen4-ultra: ASPECT_RATIO=1:1', 1, 90, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"1:1"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (252, 'KIE Auto Std gpt-image/1-5-image-to-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (252, 'KIE Auto Std gpt-image/1-5-image-to-image #1', 'Auto std rule for gpt-image/1-5-image-to-image: ASPECT_RATIO=3:2', 1, 90, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"3:2"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (253, 'KIE Auto Std gpt-image/1-5-text-to-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (253, 'KIE Auto Std gpt-image/1-5-text-to-image #1', 'Auto std rule for gpt-image/1-5-text-to-image: ASPECT_RATIO=1:1', 1, 90, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"1:1"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (254, 'KIE Auto Std gpt4o-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (256, 'KIE Auto Std grok-imagine/image-to-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (257, 'KIE Auto Std grok-imagine/text-to-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (257, 'KIE Auto Std grok-imagine/text-to-image #1', 'Auto std rule for grok-imagine/text-to-image: ASPECT_RATIO=3:2', 1, 90, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"3:2"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (258, 'KIE Auto Std grok-imagine/upscale Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (260, 'KIE Auto Std ideogram/character Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (261, 'KIE Auto Std ideogram/character-edit Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (262, 'KIE Auto Std ideogram/character-remix Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (263, 'KIE Auto Std ideogram/v3-reframe Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (267, 'KIE Auto Std qwen/image-edit Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (268, 'KIE Auto Std qwen/image-to-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (269, 'KIE Auto Std qwen/text-to-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (271, 'KIE Auto Std recraft/crisp-upscale Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (272, 'KIE Auto Std recraft/remove-background Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (273, 'KIE Auto Std seedream/4.5-edit Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (273, 'KIE Auto Std seedream/4.5-edit #1', 'Auto std rule for seedream/4.5-edit: ASPECT_RATIO=1:1', 1, 90, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"1:1"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (274, 'KIE Auto Std seedream/4.5-text-to-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (274, 'KIE Auto Std seedream/4.5-text-to-image #1', 'Auto std rule for seedream/4.5-text-to-image: ASPECT_RATIO=1:1', 1, 90, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"1:1"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (276, 'KIE Auto Std topaz/image-upscale Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (277, 'KIE Auto Std z-image Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (277, 'KIE Auto Std z-image #1', 'Auto std rule for z-image: ASPECT_RATIO=1:1', 1, 90, 0, 1, 0, 'per_call', 10, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"1:1"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (299, 'KIE Auto Std bytedance/v1-lite-image-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (299, 'KIE Auto Std bytedance/v1-lite-image-to-video #1', 'Auto std rule for bytedance/v1-lite-image-to-video: RESOLUTION_TIER=P720', 1, 90, 0, 0, 1, 'per_second', 36, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P720"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (300, 'KIE Auto Std bytedance/v1-lite-text-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (300, 'KIE Auto Std bytedance/v1-lite-text-to-video #1', 'Auto std rule for bytedance/v1-lite-text-to-video: ASPECT_RATIO=16:9, RESOLUTION_TIER=P720', 1, 100, 0, 0, 1, 'per_second', 36, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9","RESOLUTION_TIER":"P720"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (301, 'KIE Auto Std bytedance/v1-pro-fast-image-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (301, 'KIE Auto Std bytedance/v1-pro-fast-image-to-video #1', 'Auto std rule for bytedance/v1-pro-fast-image-to-video: RESOLUTION_TIER=P720', 1, 90, 0, 0, 1, 'per_second', 36, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P720"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (302, 'KIE Auto Std bytedance/v1-pro-image-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (302, 'KIE Auto Std bytedance/v1-pro-image-to-video #1', 'Auto std rule for bytedance/v1-pro-image-to-video: RESOLUTION_TIER=P720', 1, 90, 0, 0, 1, 'per_second', 36, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P720"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (303, 'KIE Auto Std bytedance/v1-pro-text-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (303, 'KIE Auto Std bytedance/v1-pro-text-to-video #1', 'Auto std rule for bytedance/v1-pro-text-to-video: ASPECT_RATIO=16:9, RESOLUTION_TIER=P720', 1, 100, 0, 0, 1, 'per_second', 36, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9","RESOLUTION_TIER":"P720"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (305, 'KIE Auto Std grok-imagine/image-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (305, 'KIE Auto Std grok-imagine/image-to-video #1', 'Auto std rule for grok-imagine/image-to-video: RESOLUTION_TIER=P480', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P480"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (306, 'KIE Auto Std grok-imagine/text-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (306, 'KIE Auto Std grok-imagine/text-to-video #1', 'Auto std rule for grok-imagine/text-to-video: ASPECT_RATIO=2:3, RESOLUTION_TIER=P480', 1, 100, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"2:3","RESOLUTION_TIER":"P480"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (308, 'KIE Auto Std hailuo/02-image-to-video-pro Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 90, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (309, 'KIE Auto Std hailuo/02-image-to-video-standard Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 90, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (309, 'KIE Auto Std hailuo/02-image-to-video-standard #1', 'Auto std rule for hailuo/02-image-to-video-standard: RESOLUTION_TIER=P768', 1, 90, 0, 0, 1, 'per_second', 90, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P768"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (310, 'KIE Auto Std hailuo/02-text-to-video-pro Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 90, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (311, 'KIE Auto Std hailuo/02-text-to-video-standard Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 90, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (312, 'KIE Auto Std hailuo/2-3-image-to-video-pro Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 90, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (312, 'KIE Auto Std hailuo/2-3-image-to-video-pro #1', 'Auto std rule for hailuo/2-3-image-to-video-pro: RESOLUTION_TIER=P768', 1, 90, 0, 0, 1, 'per_second', 90, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P768"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (313, 'KIE Auto Std hailuo/2-3-image-to-video-standard Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 90, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (313, 'KIE Auto Std hailuo/2-3-image-to-video-standard #1', 'Auto std rule for hailuo/2-3-image-to-video-standard: RESOLUTION_TIER=P768', 1, 90, 0, 0, 1, 'per_second', 90, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P768"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (315, 'KIE Auto Std kling-2.6/image-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (315, 'KIE Auto Std kling-2.6/image-to-video #1', 'Auto std rule for kling-2.6/image-to-video: ASPECT_RATIO=16:9, MODE=PRO, SOUND_SUPPORTED=TRUE', 1, 110, 0, 0, 1, 'per_second', 48, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9","MODE":"PRO","SOUND_SUPPORTED":"TRUE"}}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (315, 'KIE Auto Std kling-2.6/image-to-video #2', 'Auto std rule for kling-2.6/image-to-video: SOUND_SUPPORTED=FALSE', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"SOUND_SUPPORTED":"FALSE"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (316, 'KIE Auto Std kling-2.6/motion-control Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (316, 'KIE Auto Std kling-2.6/motion-control #1', 'Auto std rule for kling-2.6/motion-control: MODE=720P', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"MODE":"720P"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (317, 'KIE Auto Std kling-2.6/text-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (317, 'KIE Auto Std kling-2.6/text-to-video #1', 'Auto std rule for kling-2.6/text-to-video: ASPECT_RATIO=1:1, SOUND_SUPPORTED=FALSE', 1, 100, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"1:1","SOUND_SUPPORTED":"FALSE"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (321, 'KIE Auto Std kling/v2-1-master-image-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (322, 'KIE Auto Std kling/v2-1-master-text-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (322, 'KIE Auto Std kling/v2-1-master-text-to-video #1', 'Auto std rule for kling/v2-1-master-text-to-video: ASPECT_RATIO=16:9', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (323, 'KIE Auto Std kling/v2-1-pro Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (324, 'KIE Auto Std kling/v2-1-standard Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (325, 'KIE Auto Std kling/v2-5-turbo-image-to-video-pro Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (326, 'KIE Auto Std kling/v2-5-turbo-text-to-video-pro Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (326, 'KIE Auto Std kling/v2-5-turbo-text-to-video-pro #1', 'Auto std rule for kling/v2-5-turbo-text-to-video-pro: ASPECT_RATIO=16:9', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (329, 'KIE Auto Std sora-2-characters Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (331, 'KIE Auto Std sora-2-image-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (331, 'KIE Auto Std sora-2-image-to-video #1', 'Auto std rule for sora-2-image-to-video: ASPECT_RATIO=16:9', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (332, 'KIE Auto Std sora-2-pro-image-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (332, 'KIE Auto Std sora-2-pro-image-to-video #1', 'Auto std rule for sora-2-pro-image-to-video: ASPECT_RATIO=16:9', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (333, 'KIE Auto Std sora-2-pro-storyboard Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (333, 'KIE Auto Std sora-2-pro-storyboard #1', 'Auto std rule for sora-2-pro-storyboard: ASPECT_RATIO=16:9', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (334, 'KIE Auto Std sora-2-pro-text-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (334, 'KIE Auto Std sora-2-pro-text-to-video #1', 'Auto std rule for sora-2-pro-text-to-video: ASPECT_RATIO=16:9', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (335, 'KIE Auto Std sora-2-text-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (335, 'KIE Auto Std sora-2-text-to-video #1', 'Auto std rule for sora-2-text-to-video: ASPECT_RATIO=16:9', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (336, 'KIE Auto Std sora-watermark-remover Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (338, 'KIE Auto Std topaz/video-upscale Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (343, 'KIE Auto Std wan/2-2-a14b-image-to-video-turbo Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (343, 'KIE Auto Std wan/2-2-a14b-image-to-video-turbo #1', 'Auto std rule for wan/2-2-a14b-image-to-video-turbo: RESOLUTION_TIER=P720', 1, 90, 0, 0, 1, 'per_second', 36, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P720"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (344, 'KIE Auto Std wan/2-2-a14b-speech-to-video-turbo Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (344, 'KIE Auto Std wan/2-2-a14b-speech-to-video-turbo #1', 'Auto std rule for wan/2-2-a14b-speech-to-video-turbo: RESOLUTION_TIER=P480', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P480"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (345, 'KIE Auto Std wan/2-2-a14b-text-to-video-turbo Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (345, 'KIE Auto Std wan/2-2-a14b-text-to-video-turbo #1', 'Auto std rule for wan/2-2-a14b-text-to-video-turbo: ASPECT_RATIO=16:9, RESOLUTION_TIER=P720', 1, 100, 0, 0, 1, 'per_second', 36, 0, 0, 2.0, '{"standard_values":{"ASPECT_RATIO":"16:9","RESOLUTION_TIER":"P720"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (346, 'KIE Auto Std wan/2-2-animate-move Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (346, 'KIE Auto Std wan/2-2-animate-move #1', 'Auto std rule for wan/2-2-animate-move: RESOLUTION_TIER=P480', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P480"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (347, 'KIE Auto Std wan/2-2-animate-replace Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (347, 'KIE Auto Std wan/2-2-animate-replace #1', 'Auto std rule for wan/2-2-animate-replace: RESOLUTION_TIER=P480', 1, 90, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P480"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (348, 'KIE Auto Std wan/2-6-flash-image-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (348, 'KIE Auto Std wan/2-6-flash-image-to-video #1', 'Auto std rule for wan/2-6-flash-image-to-video: MULTI_SHOTS_SUPPORTED=FALSE, RESOLUTION_TIER=P1080', 1, 100, 0, 0, 1, 'per_second', 42, 0, 0, 2.0, '{"standard_values":{"MULTI_SHOTS_SUPPORTED":"FALSE","RESOLUTION_TIER":"P1080"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (349, 'KIE Auto Std wan/2-6-flash-video-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (349, 'KIE Auto Std wan/2-6-flash-video-to-video #1', 'Auto std rule for wan/2-6-flash-video-to-video: MULTI_SHOTS_SUPPORTED=FALSE, RESOLUTION_TIER=P1080', 1, 100, 0, 0, 1, 'per_second', 42, 0, 0, 2.0, '{"standard_values":{"MULTI_SHOTS_SUPPORTED":"FALSE","RESOLUTION_TIER":"P1080"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (350, 'KIE Auto Std wan/2-6-image-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (350, 'KIE Auto Std wan/2-6-image-to-video #1', 'Auto std rule for wan/2-6-image-to-video: RESOLUTION_TIER=P1080', 1, 90, 0, 0, 1, 'per_second', 42, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P1080"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (351, 'KIE Auto Std wan/2-6-text-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (351, 'KIE Auto Std wan/2-6-text-to-video #1', 'Auto std rule for wan/2-6-text-to-video: RESOLUTION_TIER=P1080', 1, 90, 0, 0, 1, 'per_second', 42, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P1080"}}', datetime('now'), datetime('now'));

INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (352, 'KIE Auto Std wan/2-6-video-to-video Base', 'Auto base rule generated from category fallback', 1, -100000, 0, 0, 1, 'per_second', 30, 0, 0, 2.0, '{"rule_kind":"base_pricing"}', datetime('now'), datetime('now'));
INSERT INTO system_api_billing_rules (system_api_id, name, description, is_active, priority, applies_to_text, applies_to_image, applies_to_video, billing_unit_type, billing_cost, billing_cost_input, billing_cost_output, charge_multiplier, extra_conditions, created_at, updated_at) VALUES (352, 'KIE Auto Std wan/2-6-video-to-video #1', 'Auto std rule for wan/2-6-video-to-video: RESOLUTION_TIER=P1080', 1, 90, 0, 0, 1, 'per_second', 42, 0, 0, 2.0, '{"standard_values":{"RESOLUTION_TIER":"P1080"}}', datetime('now'), datetime('now'));

COMMIT;