with open('backend/app/jobs/billing_reconcile.py', 'a', encoding='utf-8') as f:
    f.write('\n\ndef run_billing_reconcile_single(provider: str, task_id: str) -> Dict[str, Any]:\n')
    f.write('    \"\"\"Manual admin reconcile for a single specific provider and task_id.\"\"\"\n')
    f.write('    provider = str(provider or \"\").strip()\n')
    f.write('    task_id = str(task_id or \"\").strip()\n')
    f.write('    if not provider or not task_id:\n')
    f.write('        return {\"ok\": False, \"error\": \"provider and task_id are required\"}\n\n')
    f.write('    with SessionLocal() as db:\n')
    f.write('        api_key, resolved_endpoint, resolved_api_id = _resolve_system_api_credentials(\n')
    f.write('            db, system_api_id=None, provider=provider\n')
    f.write('        )\n')
    f.write('        query_endpoint = resolved_endpoint\n')
    f.write('        if _provider_is_kie(provider) and not query_endpoint:\n')
    f.write('            query_endpoint = \"https://api.kie.ai/api/v1/jobs/recordInfo\"\n')
    f.write('        if \"runninghub\" in provider.lower() and not query_endpoint:\n')
    f.write('            query_endpoint = \"https://www.runninghub.cn/openapi/v2/query\"\n\n')
    f.write('        if not api_key:\n')
    f.write('            return {\"ok\": False, \"error\": \"No api_key found for provider\"}\n\n')
    f.write('        usage = media_service.fetch_provider_task_usage(\n')
    f.write('            task_id=task_id,\n')
    f.write('            api_key=api_key,\n')
    f.write('            query_endpoint=query_endpoint or None,\n')
    f.write('            provider=provider,\n')
    f.write('            refresh_if_missing=True,\n')
    f.write('        )\n')
    f.write('        if not usage:\n')
    f.write('            return {\"ok\": False, \"error\": \"No usage or task found from provider\"}\n\n')
    f.write('        return {\n')
    f.write('            \"ok\": True,\n')
    f.write('            \"provider\": provider,\n')
    f.write('            \"task_id\": task_id,\n')
    f.write('            \"usage\": usage\n')
    f.write('        }\n')
