import sys
import traceback
sys.path.append('c:/AS/AIStory/backend')
from app.api.endpoints import parse_shots_markdown_table, _validate_shot_rows_roundtrip_or_raise, _parse_shot_markdown_or_raise

md_text = """| Shot ID | Shot Name | Scene ID | Shot Logic (CN) | Start Frame | Video Content | Duration (s) | Keyframes | End Frame | Start Frame (CN) | Video Content (CN) | Keyframes (CN) | End Frame (CN) | Associated Entities |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| EP01_SC01_SH01 | 鸟瞰引入与俯冲揭示 | EP01_SC01 | P1 空间建立(5s)+P2 俯冲揭示(4s)=9s。通过航拍跟随与俯冲建立世界观与悬疑，作为开场长镜头。 | [Global Style] cinematic realism, high contrast, historical weight,<br>[Context & Lighting] vast land under dim yellow sky, distant city fading into haze,<br>[Camera & Composition] Aerial Wide Shot, high angle, 24mm lens, deep depth of field,<br>[Staging & Spatial] ENV:[Xianyang City Aerial] in far background, PROP:[Black Imperial Carriage] exiting north gate at midground,<br>[Subject Action (Static)] a red-beaked crow gliding mid-air,<br>[Layers & Details] farmland textures below. | [Global Style] cinematic realism, high contrast,<br>[Camera Movement] Tracking forward following the crow, then transitioning into a rapid descending dive (dolly down + tilt down) from aerial to vertical plunge.<br>[Action Beat Chain] (P1) The crow glides steadily forward over the moving PROP:[Black Imperial Carriage], crossing fields -> resulting in spatial continuity. (P2) The crow suddenly spirals downward rapidly, syncing with rising wind SFX -> revealing ENV:[Kengru Valley] and the massive pit filled with bodies.<br>[Dynamic Atmosphere] lighting darkens gradually, shadows deepen as descent intensifies. | 9 | NO | [Global Style] cinematic realism,<br>[Context & Lighting] oppressive dim light over a massive pit,<br>[Camera & Composition] High Angle Wide Shot, 24mm lens,<br>[Staging & Spatial] ENV:[Kengru Valley] dominates frame, pit center,<br>[Subject Action (Static)] bodies densely packed below,<br>[Layers & Details] dust and faint movement. | 写实主义电影质感，高对比；昏黄天色下广阔大地，远处城池渐隐；航拍广角，24mm大景深；远景为ENV:[Xianyang City Aerial]，中景为驶出的PROP:[Black Imperial Carriage]；一只红嘴山鸦悬空滑翔；下方农田纹理清晰。 | 镜头跟随山鸦平稳前行，掠过缓慢移动的车驾与农田，保持空间连续。随后山鸦骤然收翼俯冲，镜头同步快速下压并向下倾斜，风声骤起，与俯冲节奏同步，最终揭示ENV:[Kengru Valley]巨大深坑与堆积尸体。光线逐渐压暗，阴影加重。 | NO | 写实主义风格；压抑昏暗光线笼罩深坑；高角度广角镜头；ENV:[Kengru Valley]占据画面中心；坑底尸体密集；尘土与细微动势可见。 | ENV:[Kengru Valley], PROP:[Black Imperial Carriage] |
| EP01_SC01_SH02 | 坠坑冲击 | EP01_SC01 | P1 推搡动作(2s)+P2 坠落冲击(3s)+停顿(1s)=6s。表现主角跌落与受力反应。 | [Global Style] cinematic realism,<br>[Context & Lighting] pit edge with harsh top light,<br>[Camera & Composition] Medium Shot, eye-level, 35mm lens,<br>[Staging & Spatial] CHAR:[@蒙治 (Meng Zhi)] at center foreground, guards behind in midground,<br>[Subject Action (Static)] CHAR:[@蒙治 (Meng Zhi)] hands tied behind, leaning forward slightly,<br>[Layers & Details] dirt edge visible. | [Global Style] cinematic realism,<br>[Camera Movement] Slight handheld shake with forward push, following momentum.<br>[Action Beat Chain] (P1) A guard kicks CHAR:[@蒙治 (Meng Zhi)] from behind, his body jolts forward, balance breaking -> resulting in loss of footing. (P2) He falls forward into the pit, arms bound, body rotating slightly, hitting corpse pile with a heavy thud SFX, releasing a painful cry.<br>[Dynamic Atmosphere] dust bursts upward on impact. | 6 | NO | [Global Style] cinematic realism,<br>[Context & Lighting] dim pit bottom,<br>[Camera & Composition] Medium Close-up, 35mm lens,<br>[Staging & Spatial] CHAR:[@蒙治 (Meng Zhi)] collapsed center,<br>[Subject Action (Static)] body twisted, face in pain,<br>[Layers & Details] dust cloud settling. | 写实主义风格；坑沿强顶光；中景平视35mm；CHAR:[@蒙治 (Meng Zhi)]居中，后方影卫；双手反缚身体前倾；坑边泥土清晰。 | 影卫从背后猛踹，CHAR:[@蒙治 (Meng Zhi)]身体前冲失衡，镜头轻微晃动跟随动势。他跌入坑中，身体翻转重重砸在尸体堆上，伴随沉闷撞击声与痛呼，尘土扬起。 | NO | 写实风格；坑底昏暗；中近景；CHAR:[@蒙治 (Meng Zhi)]倒地中央，身体扭曲，面露痛苦；尘土缓慢落下。 | CHAR:[@蒙治 (Meng Zhi)] |
| EP01_SC01_SH03 | 主观惊骇 | EP01_SC01 | P1 苏醒对视(2s)+P2 弹开环视(3s)+P3 视线锁定(3s)=8s。使用POV+Rack Focus强化冲击。 | [Global Style] cinematic realism,<br>[Context & Lighting] dim, claustrophobic pit interior,<br>[Camera & Composition] POV Close-up, 50mm lens,<br>[Staging & Spatial] corpse face extreme foreground, filling frame,<br>[Subject Action (Static)] corpse staring eyes fixed,<br>[Layers & Details] blurred background bodies. | [Global Style] cinematic realism,<br>[Camera Movement] Sudden backward jerk (handheld recoil) + Rack Focus shifting from corpse to environment.<br>[Action Beat Chain] (P1) CHAR:[@蒙治 (Meng Zhi)] opens eyes facing corpse inches away -> resulting in shock spike. (P2) Camera jerks backward as he recoils, breathing intensifies, scanning left-right showing bodies and executions above. (P3) Focus shifts upward toward CHAR:[@阴世贤 (Yin Shixian)] and PROP:[Black Imperial Carriage] silhouette.<br>[Dynamic Atmosphere] flickering light and drifting dust intensify suffocation. | 8 | NO | [Global Style] cinematic realism,<br>[Context & Lighting] dim pit with overhead light beams,<br>[Camera & Composition] Medium Shot, 50mm,<br>[Staging & Spatial] upward angle toward pit edge,<br>[Subject Action (Static)] CHAR:[@蒙治 (Meng Zhi)] frozen in fear,<br>[Layers & Details] silhouettes above. | 写实风格；坑底压抑光线；主观近景50mm；尸体面部贴近画面；死不瞑目；背景虚化尸体。 | 蒙治睁眼与尸体贴面，瞬间惊骇。镜头猛然后撤模拟弹开，呼吸急促，左右快速扫视，看到尸体与被杀儒生。随后视线向上抬升，焦点转移至高处的CHAR:[@阴世贤 (Yin Shixian)]与车驾轮廓。尘土漂浮，光线闪动。 | NO | 写实风格；坑底昏暗光束；中景50mm；仰视坑沿；CHAR:[@蒙治 (Meng Zhi)]僵住惊恐；上方人影隐约。 | CHAR:[@蒙治 (Meng Zhi)], CHAR:[@阴世贤 (Yin Shixian)], PROP:[Black Imperial Carriage] |
"""
headers, rows, line_count = parse_shots_markdown_table(md_text)
try:
    print(_validate_shot_rows_roundtrip_or_raise(rows, source_label="test"))
    print("VALIDATION SUCCESS")
except Exception as e:
    traceback.print_exc()
