import sys
import traceback
sys.path.append('c:/AS/AIStory/backend')
from app.api.endpoints import parse_shots_markdown_table, sanitize_llm_markdown_output

md_text = \"\"\"\\\markdown
| Shot ID | Shot Name | Scene ID | Shot Logic (CN) | Start Frame | Video Content | Duration (s) | Keyframes | End Frame | Start Frame (CN) | Video Content (CN) | Keyframes (CN) | End Frame (CN) | Associated Entities |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| EP01_SC01_SH01 | 鸟瞰引入与俯冲揭示 | EP01_SC01 | P1 空间建立(5s)+P2 俯冲揭示(4s)=9s。通过航拍跟随与俯冲建立世界观与悬疑，作为开场长镜头。 | [Global Style] cinematic realism, high contrast, historical weight,<br>[Context & Lighting] vast land under dim yellow sky, distant city fading into haze,<br>[Camera & Composition] Aerial Wide Shot, high angle, 24mm lens, deep depth of field,<br>[Staging & Spatial] ENV:[Xianyang City Aerial] in far background, PROP:[Black Imperial Carriage] exiting north gate at midground,<br>[Subject Action (Static)] a red-beaked crow gliding mid-air,<br>[Layers & Details] farmland textures below. | [Global Style] cinematic realism, high contrast,<br>[Camera Movement] Tracking forward following the crow, then transitioning into a rapid descending dive (dolly down + tilt down) from aerial to vertical plunge.<br>[Action Beat Chain] (P1) The crow glides steadily forward over the moving PROP:[Black Imperial Carriage], crossing fields -> resulting in spatial continuity. (P2) The crow suddenly spirals downward rapidly, syncing with rising wind SFX -> revealing ENV:[Kengru Valley] and the massive pit filled with bodies.<br>[Dynamic Atmosphere] lighting darkens gradually, shadows deepen as descent intensifies. | 9 | NO | [Global Style] cinematic realism,<br>[Context & Lighting] oppressive dim light over a massive pit,<br>[Camera & Composition] High Angle Wide Shot, 24mm lens,<br>[Staging & Spatial] ENV:[Kengru Valley] dominates frame, pit center,<br>[Subject Action (Static)] bodies densely packed below,<br>[Layers & Details] dust and faint movement. | 写实主义电影质感，高对比；昏黄天色下广阔大地，远处城池渐隐；航拍广角，24mm大景深；远景为ENV:[Xianyang City Aerial]，中景为驶出的PROP:[Black Imperial Carriage]；一只红嘴山鸦悬空滑翔；下方农田纹理清晰。 | 镜头跟随山鸦平稳前行，掠过缓慢移动的车驾与农田，保持空间连续。随后山鸦骤然收翼俯冲，镜头同步快速下压并向下倾斜，风声骤起，与俯冲节奏同步，最终揭示ENV:[Kengru Valley]巨大深坑与堆积尸体。光线逐渐压暗，阴影加重。 | NO | 写实主义风格；压抑昏暗光线笼罩深坑；高角度广角镜头；ENV:[Kengru Valley]占据画面中心；坑底尸体密集；尘土与细微动势可见。 | ENV:[Kengru Valley], PROP:[Black Imperial Carriage] |
| EP01_SC01_SH02 | 坑内惨景与幸存者特写 | EP01_SC01 | P1 环境特写(3s)+P2 动作发生(5s)=8s。建立绝望氛围，引出核心事件。 | [Global Style] cinematic realism, dark, gritty,<br>[Context & Lighting] dim, claustrophobic, dirty,<br>[Camera & Composition] Medium Close-up, low angle,<br>[Staging & Spatial] ENV:[Kengru Valley] pit floor,<br>[Subject Action (Static)] motionless bodies,<br>[Layers & Details] blood, dirt, scattered scholarly scrolls. | [Global Style] cinematic realism, tight framing,<br>[Camera Movement] Static, subtle tilt up.<br>[Action Beat Chain] (P1) A blood-stained hand twitches among the dead. (P2) CHAR:[Young Scholar] struggles to lift their head, gasping silently for air. | 8 | NO | [Global Style] cinematic realism,<br>[Context & Lighting] dim, focused light on face,<br>[Camera & Composition] Close-up, shallow depth of field,<br>[Staging & Spatial] CHAR:[Young Scholar] face fills frame,<br>[Subject Action (Static)] breathing heavily, eyes wide with terror,<br>[Layers & Details] sweat, grime. | 写实主义，黑暗粗糙；昏暗令人窒息，肮脏；中特写，低角度；ENV:[Kengru Valley]坑底；静止的尸体；血迹，尘土，散落的竹简。 | 固定镜头，轻微上扬。死人堆中一只沾满鲜血的手微微抽动。CHAR:[Young Scholar]挣扎着抬起头，无声地大口喘息。 | NO | 写实主义；面部微弱光线；特写，浅景深；CHAR:[Young Scholar]面部充满画面；大口喘气，眼神惊恐；汗水，污垢。 | ENV:[Kengru Valley], CHAR:[Young Scholar] |
| EP01_SC01_SH03 | 监工发现与残暴镇压 | EP01_SC01 | P1 视线转移(3s)+P2 暴力动作(5s)=8s。展现秦军的冷酷与绝望感，制造冲突。 | [Global Style] cinematic realism, tense,<br>[Context & Lighting] sudden glaring torchlight piercing the gloom,<br>[Camera & Composition] Over-The-Shoulder (OTS) from scholar to guard,<br>[Staging & Spatial] CHAR:[Young Scholar] foreground low, CHAR:[Qin Overseer Guard] background high,<br>[Subject Action (Static)] guard looking down,<br>[Layers & Details] armor glinting in firelight. | [Global Style] cinematic realism, handheld, shaky,<br>[Camera Movement] Fast pan up to the guard, then crash zoom on the weapon.<br>[Action Beat Chain] (P1) The torchlight sweeps across, landing on the scholar. (P2) CHAR:[Qin Overseer Guard] sneers, raises a heavy wooden club, and violently strikes downward out of frame. | 8 | NO | [Global Style] cinematic realism,<br>[Context & Lighting] chaotic lighting, shadow dominance,<br>[Camera & Composition] Low Angle Wide Shot, tilted,<br>[Staging & Spatial] CHAR:[Qin Overseer Guard] towering in frame,<br>[Subject Action (Static)] posing mid-strike,<br>[Layers & Details] dust kicking up. | 写实主义，紧张；突如其来的火把强光刺破昏暗；过肩镜头，从儒生看向守卫；前低后高；守卫俯视；盔甲在火光中反光。 | 手持摄影，由于不安而摇晃。镜头快速上移至守卫，然后推向武器。火光扫过，落在儒生身上。CHAR:[Qin Overseer Guard]冷笑，举起粗重的木棍，狠狠向下砸出画外。 | NO | 写实主义；混乱的光线，阴影主导；低角度广角，倾斜；CHAR:[Qin Overseer Guard]高大威猛；保持击打姿势；扬起的尘土。 | CHAR:[Young Scholar], CHAR:[Qin Overseer Guard] |
| EP01_SC01_SH04 | 死亡的主观视角 | EP01_SC01 | P1 视觉模糊(3s)+P2 完全黑场(2s)=5s。体验极度的压迫感和死亡降临。 | [Global Style] cinematic realism, subjective POV, distorted,<br>[Context & Lighting] fading light, narrowing vignette,<br>[Camera & Composition] Extreme Close-up, POV, highly blurred edges,<br>[Staging & Spatial] looking up at the club descending,<br>[Subject Action (Static)] club blurred,<br>[Layers & Details] fast motion blur. | [Global Style] cinematic realism, POV,<br>[Camera Movement] Shaking violently, then rapid plunge downward.<br>[Action Beat Chain] (P1) The club descends rapidly toward the lens. (P2) The screen violently flashes red/black, then snaps to complete darkness. | 5 | NO | [Global Style] abstract, pure black,<br>[Context & Lighting] none,<br>[Camera & Composition] none,<br>[Staging & Spatial] none,<br>[Subject Action (Static)] none,<br>[Layers & Details] pure black frame. | 写实主义，主观视角，扭曲；光线消退，周边暗角收窄；特写，POV，边缘高度模糊；仰视砸下的木棍；木棍模糊；快速运动模糊。 | 主观视角。剧烈摇晃，然后视线快速坠落。木棍朝镜头快速砸下。画面剧烈闪烁红/黑光，随后瞬间陷入完全的黑暗。 | NO | 抽象，纯黑；无光；无机位；无空间；无动作；纯黑画面。 | CHAR:[Young Scholar], CHAR:[Qin Overseer Guard] |
| EP01_SC01_SH05 | 系统提示音与奇异光芒 | EP01_SC01 | P1 黑暗静止(3s)+P2 光芒绽放(4s)=7s。从极致死亡过渡到奇幻新生，作为剧情转折点。 | [Global Style] abstract, minimalist, dark,<br>[Context & Lighting] pitch black void,<br>[Camera & Composition] none, flat,<br>[Staging & Spatial] infinite black,<br>[Subject Action (Static)] nothingness,<br>[Layers & Details] absolute silence. | [Global Style] sci-fi, ethereal, high contrast,<br>[Camera Movement] Slow push in toward the emerging light.<br>[Action Beat Chain] (P1) Absolute darkness holds. A sharp, digital "ding" is heard (implied). (P2) A brilliant, crackling blue UI interface/light bursts open from the center of the darkness, illuminating swirling dust motes. | 7 | NO | [Global Style] sci-fi, ethereal,<br>[Context & Lighting] bright blue digital glow,<br>[Camera & Composition] Medium Shot, centered,<br>[Staging & Spatial] light expanding in the void,<br>[Subject Action (Static)] hovering glowing lines,<br>[Layers & Details] dust caught in light beams. | 抽象，极简，黑暗；漆黑的虚空；无机位，平坦；无限延伸的黑；虚无；绝对的寂静。 | 科幻，空灵，高对比度。缓慢推向渐亮的光芒。维持绝对的黑暗。伴随（暗示的）清脆“叮”的一声系统提示音。黑暗中心骤然绽放出耀眼、闪烁的蓝色UI界面光芒，照亮了周围翻滚的浮尘。 | NO | 科幻，空灵；明亮的蓝色数字发光；中景，居中；光芒在虚空中扩张；悬浮的闪亮线条；光束中捕捉到的尘土。 | CHAR:[Young Scholar] |
| EP01_SC01_SH06 | 复活与仰望苍穹 | EP01_SC01 | P1 睁眼(3s)+P2 视角反转(5s)=8s。确立新生身份，引出下一个场景。 | [Global Style] cinematic realism mixed with subtle sci-fi glow,<br>[Context & Lighting] blue light reflecting on a dirty face,<br>[Camera & Composition] Extreme Close-up on eye,<br>[Staging & Spatial] macro eye shot,<br>[Subject Action (Static)] iris contracting,<br>[Layers & Details] reflection of UI in eye. | [Global Style] cinematic realism/sci-fi blend,<br>[Camera Movement] Pull back and tilt up rapidly from the eye to the sky.<br>[Action Beat Chain] (P1) The eye snaps open, pupil contracting, reflecting the blue light. (P2) The camera smoothly pulls back over the rim of the pit, revealing the vast, dark sky and the silhouette of the carriage vanishing into the distance. | 8 | NO | [Global Style] cinematic realism, vast scale,<br>[Context & Lighting] deep twilight, faint blue glow below,<br>[Camera & Composition] Low Angle Extreme Wide Shot,<br>[Staging & Spatial] looking out from the pit, carriage tiny on horizon,<br>[Subject Action (Static)] clouds moving slowly,<br>[Layers & Details] stars piercing the gloom. | 电影写实与微弱科幻光晕融合；蓝光映照在肮脏的脸上；眼部极度特写；微距眼球；瞳孔收缩；眼中反射出UI界面。 | 写实/科幻融合风格。镜头从眼睛快速后拉并向上倾斜。眼睛猛然睁开，瞳孔收缩，倒映着蓝光。镜头平滑后拉，越过坑的边缘，揭示广阔黑暗的天空以及远去车驾的剪影。 | NO | 写实主义，宏大规模；深邃黄昏，下方微弱蓝光；低角度极广角；从坑底向外望，地平线上渺小的车驾；云层缓慢移动；星光穿透幽暗。 | CHAR:[Young Scholar], PROP:[Black Imperial Carriage] |
\\\\"\"\"

print("Testing markdown parser via sanitize_llm...")
response_content = sanitize_llm_markdown_output(md_text)
print("Sanitized content length:", len(response_content))

import re
reasoning_prefix_terms = [
    "i will", "let me", "let's", "analysis", "reasoning", "thought process",
    "分析", "思路", "推理", "我将", "我认为", "我認為",
]
escaped_terms = [re.escape(term) for term in reasoning_prefix_terms if str(term or "").strip()]
reasoning_line_re = re.compile(
    r"^\s*(?:" + "|".join(escaped_terms) + r")\b",
    flags=re.IGNORECASE,
)
cleaned_lines = []
for line in str(response_content or "").splitlines():
    stripped = line.strip()
    if stripped and not stripped.startswith("|") and reasoning_line_re.match(stripped):
        continue
    cleaned_lines.append(line)
response_content = "\n".join(cleaned_lines).strip()

headers, shots_data, table_line_count = parse_shots_markdown_table(response_content)
print(f"Parsed rows count: {len(shots_data)}")
print(f"Table line count: {table_line_count}")

if table_line_count >= 4 and len(shots_data) > 0 and (len(shots_data) * 2) <= table_line_count:
    print(f"FAILED safety check! (shots_data: {len(shots_data)}, table_line_count: {table_line_count})")
else:
    print("PASSED safety check!")
